name: Deploy Hugo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build for GitHub
        run: hugo --minify --baseURL "https://blog.brez.top" -d ./public_github

      - name: Build for Server
        run: hugo --minify --baseURL "https://gblog.brez.top" -d ./public_server

      - name: Deploy to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_github
          publish_branch: gh-pages
          cname: blog.brez.top

      - name: Deploy to Server Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_server
          publish_branch: server-dist